export const chrismastGifts: string[] = [
    "Auriculares inalámbricos",
    "Smartwatch",
    "Tablet",
    "Laptop",
    "Smartphone",
    "Videojuego",
    "Consola de videojuegos",
    "Teclado mecánico",
    "Mouse gamer",
    "Monitor",
    "Set de Lego",
    "Muñeca",
    "Pelota de fútbol",
    "Balón de baloncesto",
    "Bicicleta",
    "Patineta",
    "Scooter eléctrico",
    "Dron",
    "Cámara instantánea",
    "Altavoz Bluetooth",
    "Caja de chocolates",
    "Perfume",
    "Reloj clásico",
    "Bolso elegante",
    "Mochila",
    "Cartera",
    "Zapatillas deportivas",
    "Pijama navideña",
    "Sudadera",
    "Bufanda de lana",
    "Guantes de cuero",
    "Abrigo",
    "Gorra",
    "Joyería (collar/anillo)",
    "Juego de mesa",
    "Rompecabezas",
    "Kit de arte",
    "Instrumento musical",
    "Set de cocina",
    "Taza personalizada",
    "Suscripción a streaming",
    "Suscripción a gimnasio",
    "Entrada a un concierto",
    "Viaje sorpresa",
    "Bono de regalo Amazon",
    "Tarjeta de Netflix",
    "Lámpara LED",
    "Decoración navideña",
    "Peluches",
    "Libros de aventuras",
    "Agenda 2025"
];